### ISSUE TITLE
slow building 

### ISSUE THREAD

**Issue by LijinPengT** [eth-sri/zkay#1]
+ When I executing ./install-zokrates.sh, it was so slow building. 
+ And it is difficult to use docker for Chinese. Is there a clear README.md for use zkay on the host.

**Comment by bichselb** [comment]
Re slow building: We are not planning on improving this. As a one-time effort, this seems like a non-issue.

Re docker for Chinese: We are not planning on translating this project to other languages.

Re installing on host: Follow the comments in the [Dockerfile](https://github.com/eth-sri/zkay/blob/master/install/Dockerfile), marked by `To install on host`.
