### ISSUE TITLE
Minimum RAM memory requirement for running homomorphic_crypto_backend "paillier"

### ISSUE THREAD

**Issue by Hanseltu** [eth-sri/zkay#9]
Hi,

May I ask what is the minimum RAM requirement for running "paillier"? I run it on a 16GB RAM laptop but I got the following error:

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/19731522/237040424-3df274ad-65d8-4a9d-9b3d-801b12cb3391.png">

Any solution to safely run it within 16 GB? Thanks for your help!

**Comment by sam-steffen** [comment]
Hi

The Paillier cryptosystem is extremely memory intensive. As we describe on page 10 [here](https://files.sri.inf.ethz.ch/website/papers/sp22-zeestar.pdf), using Groth16+Paillier with 2048-bit keys required over 256 GB of RAM in our experiments. This backend is only included for research purposes.

Instead, you should use the "elgamal" crypto backend enabled by default [here](https://github.com/eth-sri/zkay/blob/920e883c095f456770c03606021c728b34497f42/zkay/config_user.py#LL46C12-L46C12). This backend is significantly more efficient (4 GB of RAM should suffice).
